### ISSUE TITLE
Move HTML files to the folder within the scroller app

### ISSUE THREAD

**Issue by pjayathissa** [buds-lab/learning-trail-scroller-demo#13]
The new HTML files produced in your pull request are in the root github folder, not the scroller app folder. As a result, they are not rendering in the final version.

**Comment by tapeesh** [comment]
@pjayathissa Should I remove the HTML files which are not required then? only keep the updated ones right?

**Comment by pjayathissa** [comment]
Done with tapeesh's billion commits
